### ISSUE TITLE
Module Causes huge lag in Foundry

### ISSUE THREAD

**Issue by GambetTV** [eXaminator/foundry-animation-preview#1]
I've been waiting for a module like this for a long time, so I'm super happy you made it! Unfortunately, I've been noticing when I try to use it, it seems to cause Foundry to either break entirely, or at least suffer from huge lag. So far the only way I've been able to fix it is by closing out of Foundry and restarting it from scratch. It doesn't seem to cause the lag right away, only when I actually hover my mouse over a video file.

My best guess is that some of my images are quite large, like, 150 MB files in some cases, so maybe that is behind it. I'm not sure if that's something that can be fixed if so, but I figured I'd point it out just in case.

**Comment by eXaminator** [comment]
Hi GambetTV, thanks for the issue!

I did notice some performance issues when it came to folders with a lot of video files, so I'll probably revisit this sometime soon and see if I can improve the performance somehow, probably by deferring the loading of the video a bit. I'll look into it and see what I can do!

**Comment by eXaminator** [comment]
Hi @GambetTV,

I deferred the video loading in version 1.0.1. While this is in general less convenient (as you don't get proper previews anymore and it will take a moment to load the file when hovering), I hope that this will improve performance issues, especially with list with a lot of and/or large files.

Please let me know if this issue is resolved for you. Thanks!
